### Viendo Peticiones.
###------------------------------------
# Metodos o Verbos 
###------------------------------------

# GET - ies21
GET https://ies21.edu.ar/
###------------------------------------

# GET - Mockapi
GET https://69cbcb780b417a19e07b42c1.mockapi.io/api/v1/Productos
###------------------------------------

# GET - local
GET http://localhost:3000
###------------------------------------
#POST - local
POST http://localhost:3000
Content-Type: 'text/plain'

Contenido mas largo

###------------------------------------
#PUT - local
PUT http://localhost:3000
###------------------------------------
#DELETE - local
DELETE  http://localhost:3000